AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { ignored_files: ['db/migrate/20180425171904_create_configuracion_tutoriales.rb'] }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 5 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 10 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { ignored_files: ['planes_controller.rb', 'registrations_controller.rb', 'sessions_controller.rb', 'omniauth_callbacks_controller.rb', 'configuracion_impuestos_controller.rb', 'boleta_pagos_controller.rb', 'bimestres_controller.rb'], except_methods: ['UsuariosController#simulacion_data', 'ApiV1Controller#method_missing', 'ApiV1Controller#respond_to_missing?'] }
RemoveUnusedMethodsInHelpersCheck: { ignored_files: ['notificacion_helpers.rb', 'factura_helpers.rb', 'string_helpers.rb', 'assets_helpers.rb', 'date_helpers.rb', 'pdf_helpers.rb', 'bimestre_helpers.rb', 'conversion_helpers.rb'] , except_methods: [] }
RemoveUnusedMethodsInModelsCheck: { except_methods: ['Recibo#nombre_pdf', 'NotaCreditoDev#nombre_pdf', 'Factura#nombre_pdf', 'User#meses_liquidables', 'User#bimestres_liquidables', 'Mes#rol_ilimitado', 'Mes#rol_limitado', 'Bimestre#rol_ilimitado' ,'Bimestre#rol_limitado' ,'Mes#tickets_alimentacion', 'Mes#salario_vacacional', 'Bimestre#ultimo_aporte_bps_notarial' ,'Recibo#numero_ultimo_recibo', 'NotaCreditoDev#numero_ultima_nota', 'Mes#suma_ingresos_en_pesos', 'Mes#total_ingresos', 'FacturaCompra#iva_uyu', 'NotaCreditoDev#subtotal_pesos', 'Factura#subtotal_pesos', 'NotaCreditoDev#calcular_iva_pesos', 'Factura#calcular_iva_pesos', 'InformacionFonasa#calcular_fonasa', 'Plan#tipo.to_sym', 'NotaCreditoDev#calcular_retencion', 'Factura#calcular_retencion', 'User#role?', 'Mes#dias_hasta_vencimiento', 'Mes#set_notificacion', 'Bimestre#set_notificacion', 'Notificacion#recordatorio_fonasa', 'Notificacion#leida!', 'Notificacion#no_leidas', 'Notificacion#leidas', 'Mes#no_liquidados', 'Mes#liquidados', 'Bimestre#fonasa_liquidado', 'User#meses_anteriores_alta', 'Factura#datos_bimestre', 'Factura#cobrada?', 'Bimestre#liquidado!', 'Bimestre#liquidados', 'Factura#to_ui', 'Factura#to_usd', 'Bimestre#sin_liquidar', 'User#boleta_bps', 'Bimestre#por_mes', 'Bimestre#anio_actual', 'Bimestre#importe_sin_iva', 'Bimestre#calcular_fonasa', 'Mes#calcular_fonasa', 'Mes#importe_sin_iva', 'Factura#items_size', 'NotaCreditoDev#items_size', 'Factura#editable?', 'Mes#total_facturado', 'Mes#anio_actual', 'Mes#data_clientes_mensual', 'User#data_clientes_anual', 'User#mes_actual', 'User#nro_ultima_factura', 'Suscripcion#set_notificacion', 'Transaccion#listables', 'Transaccion#fecha_pago', 'Bimestre#codigo_barras', 'Bimestre#humanized_irpf'] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { ignored_files: ['declaracion_jurada_mailer.rb' ,'admin_user_mailer.rb', 'plan_mailer.rb', 'notificacion_mailer.rb', 'factura_mailer.rb', 'recibo_mailer.rb', 'nota_mailer.rb']}
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
